#!/usr/bin/env python3
"""Generate books.py from alfred-lectionary's BOOKS table.

One source of truth for SBL spellings, shared with that sibling repo rather than
retyped. Run after alfred-lectionary changes; the output is committed, so nothing
else here needs that repo present. The abbreviations themselves follow the SBL
Handbook of Style, 2nd ed.
"""
import importlib.util, os, sys

RESOLVE = os.path.expanduser("~/Projects/alfred-lectionary/resolve.py")
OUT = os.path.join(os.path.dirname(__file__), "..", "books.py")

spec = importlib.util.spec_from_file_location("resolve", RESOLVE)
mod = importlib.util.module_from_spec(spec)
sys.modules["resolve"] = mod
try:
    spec.loader.exec_module(mod)
except SystemExit:
    pass

books = getattr(mod, "BOOKS", None)
if not books:
    sys.exit(f"no BOOKS table in {RESOLVE}")

rows = {}
for slug, display, aliases in books:
    sbl = aliases[0] if aliases else display
    for key in {display.lower(), sbl.lower(), *(a.lower() for a in aliases)}:
        rows[key] = sbl

with open(OUT, "w", encoding="utf-8") as f:
    f.write('"""GENERATED by tools/gen_books.py -- do not edit.\n\n')
    f.write("Source: the BOOKS table in the sibling alfred-lectionary repo's resolve.py.\n"
            "Maps any book spelling (lowercased) to its SBL abbreviation, per the SBL\n"
            "Handbook of Style, 2nd ed. Committed, so the sibling repo is not needed.\n"
            '"""\n\n')
    f.write("BOOKS = {\n")
    for key in sorted(rows):
        f.write(f'    "{key}": "{rows[key]}",\n')
    f.write("}\n")
print(f"wrote {OUT} ({len(rows)} spellings, {len(books)} books)")
